### ISSUE TITLE
Documento pdf con la tabla de dependencias de estados de la clase Parque.

### ISSUE THREAD

**Issue by jrg1013** [rmt0009alu/Practica3_PCTR_DependenciasEstados#14]
Creación de un pdf con la tabla de dependencias de estado.

**Comment by jrg1013** [comment]
Primer boceto: 
![image](https://user-images.githubusercontent.com/74461986/161138955-7997aae9-671b-4484-8cac-e69a11ed1587.png)

**Comment by rmt0009alu** [comment]
@jrg1013 Validado por profesor
