### ISSUE TITLE
Decidir si aplicamos el Patrón Singleton al Parque

### ISSUE THREAD

**Issue by rmt0009alu** [rmt0009alu/Practica3_PCTR_DependenciasEstados#8]
Tomar esta decisión implica modificar, ligeramente, el código original aportado por los profesores.

**Comment by jrg1013** [comment]
En la reunión del 31/03 se probaron un par de opciones y no se estimo necesario implementarlo con Singleton

**Comment by jrg1013** [comment]
No se implementa.
